// Generated by Frozen Sand Particle Studio
// Mon Aug 11 12:11:31 2008

textures/null_test/aaa_teapot_1
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_2
	{
		animmap 16 textures/null_test/teapot0000.tga textures/null_test/teapot0001.tga textures/null_test/teapot0002.tga textures/null_test/teapot0003.tga textures/null_test/teapot0004.tga textures/null_test/teapot0005.tga textures/null_test/teapot0006.tga textures/null_test/teapot0007.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0008.tga textures/null_test/teapot0009.tga textures/null_test/teapot0010.tga textures/null_test/teapot0011.tga textures/null_test/teapot0012.tga textures/null_test/teapot0013.tga textures/null_test/teapot0014.tga textures/null_test/teapot0015.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_2
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_3
	{
		animmap 16 textures/null_test/teapot0016.tga textures/null_test/teapot0017.tga textures/null_test/teapot0018.tga textures/null_test/teapot0019.tga textures/null_test/teapot0020.tga textures/null_test/teapot0021.tga textures/null_test/teapot0022.tga textures/null_test/teapot0023.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0024.tga textures/null_test/teapot0025.tga textures/null_test/teapot0026.tga textures/null_test/teapot0027.tga textures/null_test/teapot0028.tga textures/null_test/teapot0029.tga textures/null_test/teapot0030.tga textures/null_test/teapot0031.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_3
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_4
	{
		animmap 16 textures/null_test/teapot0032.tga textures/null_test/teapot0033.tga textures/null_test/teapot0034.tga textures/null_test/teapot0035.tga textures/null_test/teapot0036.tga textures/null_test/teapot0037.tga textures/null_test/teapot0038.tga textures/null_test/teapot0039.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0040.tga textures/null_test/teapot0041.tga textures/null_test/teapot0042.tga textures/null_test/teapot0043.tga textures/null_test/teapot0044.tga textures/null_test/teapot0045.tga textures/null_test/teapot0046.tga textures/null_test/teapot0047.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_4
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_5
	{
		animmap 16 textures/null_test/teapot0048.tga textures/null_test/teapot0049.tga textures/null_test/teapot0050.tga textures/null_test/teapot0051.tga textures/null_test/teapot0052.tga textures/null_test/teapot0053.tga textures/null_test/teapot0054.tga textures/null_test/teapot0055.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0056.tga textures/null_test/teapot0057.tga textures/null_test/teapot0058.tga textures/null_test/teapot0059.tga textures/null_test/teapot0060.tga textures/null_test/teapot0061.tga textures/null_test/teapot0062.tga textures/null_test/teapot0063.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_5
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_6
	{
		animmap 16 textures/null_test/teapot0064.tga textures/null_test/teapot0065.tga textures/null_test/teapot0066.tga textures/null_test/teapot0067.tga textures/null_test/teapot0068.tga textures/null_test/teapot0069.tga textures/null_test/teapot0070.tga textures/null_test/teapot0071.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0072.tga textures/null_test/teapot0073.tga textures/null_test/teapot0074.tga textures/null_test/teapot0075.tga textures/null_test/teapot0076.tga textures/null_test/teapot0077.tga textures/null_test/teapot0078.tga textures/null_test/teapot0079.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_6
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_7
	{
		animmap 16 textures/null_test/teapot0080.tga textures/null_test/teapot0081.tga textures/null_test/teapot0082.tga textures/null_test/teapot0083.tga textures/null_test/teapot0084.tga textures/null_test/teapot0085.tga textures/null_test/teapot0086.tga textures/null_test/teapot0087.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0088.tga textures/null_test/teapot0089.tga textures/null_test/teapot0090.tga textures/null_test/teapot0091.tga textures/null_test/teapot0092.tga textures/null_test/teapot0093.tga textures/null_test/teapot0094.tga textures/null_test/teapot0095.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_7
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.5
	q3map_cloneshader textures/null_test/aaa_teapot_8
	{
		animmap 16 textures/null_test/teapot0096.tga textures/null_test/teapot0097.tga textures/null_test/teapot0098.tga textures/null_test/teapot0099.tga textures/null_test/teapot0100.tga textures/null_test/teapot0101.tga textures/null_test/teapot0102.tga textures/null_test/teapot0103.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0104.tga textures/null_test/teapot0105.tga textures/null_test/teapot0106.tga textures/null_test/teapot0107.tga textures/null_test/teapot0108.tga textures/null_test/teapot0109.tga textures/null_test/teapot0110.tga textures/null_test/teapot0111.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}

textures/null_test/aaa_teapot_8
{
	qer_editorimage textures/null_test/teapot0000.tga
	surfaceparm nonsolid
	surfaceparm nodlight
	surfaceparm trans
	surfaceparm nomarks


	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.125
	deformvertexes move 0 0 8000 square 0.5 0.5 0 0.25
	deformvertexes move 0 0 8000 square 0.5 0.5 0.5 0.5
	//q3map_cloneshader textures/null_test/aaa_teapot_8
	{
		animmap 16 textures/null_test/teapot0112.tga textures/null_test/teapot0113.tga textures/null_test/teapot0114.tga textures/null_test/teapot0115.tga textures/null_test/teapot0116.tga textures/null_test/teapot0117.tga textures/null_test/teapot0118.tga textures/null_test/teapot0119.tga
		blendfunc blend
		alphagen wave square 0 1 0 1
	}
	{
		animmap 16 textures/null_test/teapot0120.tga textures/null_test/teapot0121.tga textures/null_test/teapot0122.tga textures/null_test/teapot0123.tga textures/null_test/teapot0124.tga textures/null_test/teapot0125.tga textures/null_test/teapot0126.tga textures/null_test/teapot0127.tga
		blendfunc blend
		alphagen wave square 0 1 0.5 1
	}
}



/////////////////////////////////////////////////////////////////
